### ISSUE TITLE
Entrypoint Error

### ISSUE THREAD

**Issue by BLOKBUSTR** [SmushyTaco/Human-Reborn#3]
https://gist.github.com/BLOKBUSTR/11634977e18c80bf9602ec9ec1375f8b

I initially experienced this crash in a heavily modded instance, so I tested this mod in a bare-bones test instance with only necessary dependencies, which only gave the same results.

**Comment by SmushyTaco** [comment]
Can't replicate, shouldn't be a problem on the latest version either.
