### ISSUE TITLE
[Suggestion] Let humans spawn in daytime in the overworld?

### ISSUE THREAD

**Issue by GuyFromTheInternet** [SmushyTaco/Human-Reborn#5]
They only spawn as hostile entities and cant be spawned as regular creatures at day, can you please let them do that, I remember the humans mod always putting them on the surface

**Comment by SmushyTaco** [comment]
They don't burn in the daylight but they also don't spawn in the day. Since they're hostile mobs I'm not going to be letting them spawn during the day.
